### ISSUE TITLE
The mapping data types are incorrect

### ISSUE THREAD

**Issue by fishcodelib** [nuodb/nuodb-dotnet#18]
https://github.com/nuodb/nuodb-dotnet/search?utf8=%E2%9C%93&q=case+DbType.Date%3A+return+%22System.Date%22%3B
Incorrect:
case DbType.Date: return "System.Date";
case DbType.Time: return "System.Time";
case DbType.Binary: return "System.Binary";

Correct:
case DbType.Date: return "System.DateTime";
case DbType.Time: return "System.DateTime";
case DbType.Binary: return "System.Object";

**Comment by albymassari** [comment]
Thanks for reporting this. The bogus types have been removed
