### ISSUE TITLE
Missing data types in DataTypes.xml

### ISSUE THREAD

**Issue by fishcodelib** [nuodb/nuodb-dotnet#20]
The file 'NuoDb.Data.Client.DataTypes.xml' lacks the following data types:
blob, boolean, bytes, clob, double, enum, number

**Comment by plothridge** [comment]
Thank you for the report, [fishcodelib](https://github.com/fishcodelib).
Issue opened (internal): [DB-10290](http://tools/jira/browse/DB-10290)
