### ISSUE TITLE
eliminate dead code

### ISSUE THREAD

**Issue by gittywithexcitement** [nuodb/nuodb-dotnet#21]
[Here](https://github.com/nuodb/nuodb-dotnet/blob/4f9e6e43c61e0450670707baaefc69f7b748e60c/NuoDb.Data.Client/EncodedDataStream.cs#L354) and [here](https://github.com/nuodb/nuodb-dotnet/blob/4f9e6e43c61e0450670707baaefc69f7b748e60c/NuoDb.Data.Client/EncodedDataStream.cs#L399) is always dead code because `n > 0` is mutually exclusive with `n == 0`.

Note this means the byte count of the value 0 is 1 byte instead of 0 bytes.

**Comment by mjmichaels** [comment]
Thanks @gittywithexcitement - I recorded this in Jira as DB-10780.
