### ISSUE TITLE
dead code in encodeDouble 

### ISSUE THREAD

**Issue by gittywithexcitement** [nuodb/nuodb-dotnet#22]
I think there is dead code in [encodeDouble](https://github.com/nuodb/nuodb-dotnet/blob/4f9e6e43c61e0450670707baaefc69f7b748e60c/NuoDb.Data.Client/EncodedDataStream.cs#L1529-L1534). `count` is never used, so all of those lines are extraneous.

**Comment by mjmichaels** [comment]
Thanks. I will add this to Jira DB-10780.
