### ISSUE TITLE
Named Parameter

### ISSUE THREAD

**Issue by michaelsogos** [nuodb/nuodb-dotnet#25]
Hi,

Seems that NuoDBCommand don't use the NuoDBParameter.ParameterName = "@something".

**Comment by cincuranet** [comment]
Can you show some code?

**Comment by michaelsogos** [comment]
Sure,

Typically my query is something like:
SELECT T.* FROM MyTable T ... Joins ... WHERE T.Field1 = @p1 AND T.Field2 = @p2

And what i'd like to do is:
NuoDBCommand.Parameters.Add( new NuoDBParameter() { ParameterName = "@p1", Value = "something"})
Etc.

At the moment my workaround is:
SELECT T.* FROM MyTable T ... Joins ... WHERE T.Field1 = ? AND T.Field2 = ?
NuoDBCommand.Parameters.Add( new NuoDBParameter() { SourceColumnName = "T.Field1", Value = "something"})

Me and my team are working on brand new LOB software that is db-agnostic and we glad to add support to NuoDB because it seems to be Amazing (we take a lot of attention to scalability 😃); but to be honest the ADO.NET seems lack some features or force us to work in a less optimized way than Oracle or MySql .net drivers.

**Comment by albymassari** [comment]
Hi Michael,
there is a bug in the preparation of the SQL string that makes the last parameter ignore the @ character. As a temporary workaround, try adding an extra space at the end of the string.

Alberto

**Comment by albymassari** [comment]
Fixed in version 2.3.0.4
