### ISSUE TITLE
MARS or Batch query support

### ISSUE THREAD

**Issue by michaelsogos** [nuodb/nuodb-dotnet#26]
Hi,

is very useful to have mars or batch support.
Seems that semicolon between query isn't enough, and the server return an syntax error.

**Comment by cincuranet** [comment]
This is the "limitation" - design choice - of NuoDB's protocol. You cannot send multiple commands in batch. One `ExecuteXxx` is one statement.

**Comment by michaelsogos** [comment]
Hi,


Thank you for the quick answer 😊.


I found a workaround; I open a DBConnection, create a DBCommand associated to the DBConnecion, create a DBDataAdapter associated to the DBCommand; then for each query to execute i change the DBCommand.CommandText property (and reset DBCommand.Parameters if needed) and call DBDataAdapter.Fill() method.


Seems that everything is working pretty well.

I did it in this way to not waste memory comsuption creating every time a DBCommand.


What do you think about this solution? Any tips?






-=-=-
Michael Sogos
GuruStudioWeb





Da: Jiri {x2} Cincura
Data invio: ‎lunedì‎ ‎10‎ ‎agosto‎ ‎2015 ‎10‎:‎22
A: nuodb/nuodb-dotnet
Cc: Michael Sogos





This is the "limitation" - design choice - of NuoDB's protocol. You cannot send multiple commands in batch. One ExecuteXxx is one statement.

**Comment by cincuranet** [comment]
Yep. That's viable.
