### ISSUE TITLE
Exception thrown: 'Null object cannot be converted to a value type.' in NuoDbDataReader.cs

### ISSUE THREAD

**Issue by fishcodelib** [nuodb/nuodb-dotnet#29]
The following code will throw an exception when the value is null.
return Convert.ChangeType(value, declaredType); --> Null object cannot be converted to a value type.
ps. This issue is happening since version 2.3.0.5.

**Comment by albymassari** [comment]
Thanks for reporting this; it's fixed in 2.3.0.7
