### ISSUE TITLE
NuoDbParameter - Decimal Value 0 - 100% CPU Load

### ISSUE THREAD

**Issue by trynn** [nuodb/nuodb-dotnet#30]
Hi,
if i try to insert a record into a table, with a decimal field and fill the value within c# with a decimal value of 0, it seems the driver is hanging (and produces 100% cpu load).

Simple Table DDL
create table T1 (ID integer, VALUE numeric(15,2));

Attached a VS2015 Example with Driver Version 2.3.0.7

[synesc.NuoDbDecimal.zip](https://github.com/nuodb/nuodb-dotnet/files/539324/synesc.NuoDbDecimal.zip)

**Comment by albymassari** [comment]
Thanks for the bug report; it is fixed now
