### ISSUE TITLE
decimal value is saves as 0 in nuodb (for example 30000)

### ISSUE THREAD

**Issue by trynn** [nuodb/nuodb-dotnet#31]
Hi,
if i try to insert a record into a table, with a decimal field and fill the value within c# with a decimal value of 30000, there will be stored value 0 into the database.

Simple Table DDL
create table T1 (ID integer, VALUE numeric(15,2));

Attached a VS2015 Example with Driver Version 2.3.0.8 (also happening with 2.3.0.7)
[synesc.NuoDbDecimal.zip](https://github.com/nuodb/nuodb-dotnet/files/545905/synesc.NuoDbDecimal.zip)

**Comment by albymassari** [comment]
In my test the C# driver is able to get back the value 30000; however, the server is unable to apply the negative scaling factor, so I have pushed a change to avoid specifying them. Try with the latest 2.3.0.9 release
